### ISSUE TITLE
certain errors on server can prevent the server from resuming normal operation

### ISSUE THREAD

**Issue by kleetus** [bitpay/bwdb#11]
Doing so will render the bwdb inoperable

Steps to reproduce: 

1. start fresh with no client/server configs
2. start bwdb --regtest
3. generate 150 blocks
4. bwdb-cli createWallet test1
5. bwdb-cli importAddresses test1 wallet.dat
6. bwdb-cli createWallet test2
7. bwdb-cli importAddresses test2 wallet.dat

TypeError: Invalid hex string   at Function.WalletAddressMap.fromBuffer (/Users/chrisk/source/bwdb/lib/models/address-map.js:39:19)     

server becomes useless after the error.

**Comment by braydonf** [comment]
Looks like the issues that was causing his has been fixed, and with this commit https://github.com/bitpay/bwdb/commit/fb43a7e51044a774ccc7012f32ae53f3e0612729 the server should shutdown in such a case, letting upstart/systemd restart the process.
