### ISSUE TITLE
certain conditions can prevent a dbi from opening, node process hangs

### ISSUE THREAD

**Issue by kleetus** [bitpay/bwdb#14]
steps to reproduce: 

it might be hard to reproduce because I am not sure what causes it. 

1. you need to have a db already created. this does not seem to happen when there is no db when starting the server.
2. issue db.env.openDbi('some db'...
3. the node process will forever block on this call.

**Comment by braydonf** [comment]
Not sure if this is related; however, a openDbi typically will require a write transaction, and if there is already a write transaction for the environment, that could block while it's waiting. That is unless openDbi called with readOnly flag.
