### ISSUE TITLE
Problem with UTXO and Txids

### ISSUE THREAD

**Issue by ZebPayDhruvil** [bitpay/bwdb#15]
Version -1.0.0-beta
I started bwdb with pre-downloaded blockchain data that was used for bitcore
I created a wallet added some addresses 
Upon GET /wallets/:walletId/balance I get the proper balance.
But on GET /wallets/:walletId/txids , GET /wallets/:walletId/utxos, GET /wallets/:walletId/transactions
I get empty transaction list.

**Comment by viperikjo** [comment]
thx u
