### ISSUE TITLE
Can't import addresses using bwdb-cli command "importAddresses"

### ISSUE THREAD

**Issue by anonyxuser1** [bitpay/bwdb#16]
Hi there,

First of all thank you so much for the script and for your time. 

I seem to be having an issue here using bwdb on linux and feel like I have tried everything to get it to work. First it was 2 weeks trying to get NPM to work lol, finally got that down. I have tried the same command on the TestNet network and it seems the command "importAddresses" works perfectly fine. However, when needing to use the main bitcoin network, the bwdb-cli command "importAddresses" returns me the below error. The error below is after successfully adding a wallet with bwdb-cli, and even successfully importing a single address using the "importAddress" command, but it just doesn't want to allow me to import multiple addresses at a time for some reason thus I am not able to use the command "importAddresses" on the main network. Am I doing something wrong?
Thank you so much for your time!

Exact terminal command I am using...
`$ ./bwdb-cli importAddresses w1 xxx.json`

The error the above command returns...
```
/home/x/bwdb/node_modules/progress/lib/node-progress.js:51
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^
Error: total required
    at new ProgressBar (/home/x/bwdb/node_modules/progress/lib/node-progress.js:51:49)
    at /home/x/bwdb/bin/bwdb-cli:137:24
    at /home/x/bwdb/lib/utils.js:94:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:490:3)
```

System Specs:
- Manjaro / Arch Linux
- MSI X370 Gaming Pro Carbon
- 32 core processor at 4.1GHz
- 128GB RAM at 2933MHz
- geForce GTX 1080 Ti
- ASUS PCE-AC88 Network Card

 ******* USERS GETTING ERRORS WITH NPM / NODEJS READ BELOW *******

If anyone is trying to get their NPM to work do the following on preferably a fresh system.

1.) first install nvm using the command below:
`$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash`

2.) then install a stable later version of nodejs and npm:
`$ nvm install 8.0.0`

3.) then tell nvm to use that version:
`$ nvm use 8.0`

... after that nodejs and npm should all be ready to fly and go ahead and install bwdb successfully! :)

**Comment by gabegattis** [comment]
This project is no longer being maintained.  Take a look at https://github.com/bitpay/bitcore/tree/v8.0.0
